import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const ztNature = localFont({
  src: [
    {
      path: "./fonts/ztnature/ZTNature-Regular.woff2",
      weight: "400",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={ztNature.className}>
      <body className={"antialiased"}>{children}</body>
    </html>
  );
}
